# Preface {.unnumbered}

## DRAFT

The information contained in this [Quarto](https://quarto.org/){target="_blank"} book aims to comprehensively address the most important questions related to deploying open source solutions for clinical data analytics in the pharmaceutical and vaccine development industry.

-   What questions have been asked and ***already answered***?
-   What questions have been asked and ***nearly answered***?
-   What questions have been asked and ***not yet answered***?

We are developing this manuscript in the open and accepting contributions by the community via our GitHub repository's [Discussions](https://github.com/phuse-org/OSTCDA/discussions){target="_blank"} tab. Please contribute your thoughts, perspectives, references, citations, and links through that mechanism. We'd like to be able to attribute your ideas to you, so providing the rationale supporting your thoughts will strengthen your argument. Please be as thoughtful and thorough in your contributions as you can! You can also upvote questions and/or responses that you find particularly valuable.

#### DO NOT CITE

At the moment, this document is in draft form, hence please [***DO NOT CITE***]{.underline} it as a reference.

#### LEARN MORE

To learn more about this initiative, please watch our [2023 R in Pharma](https://rinpharma.com/){target="_blank"} lightning talk: [The State of Open Source Technology in Clinical Data Analysis, Reporting, and Submissions](https://www.youtube.com/watch?v=cbFzcXMOfTM){target="_blank"}.

## How to Contribute

Contribute to the discussion here in GitHub Discussions:\
[What is open source?](https://github.com/phuse-org/OSTCDA/discussions/1){target="_blank"}

## Guidance

-   Provide your thoughts and perspectives
-   Provide references to articles, webinars, presentations (citations, links)
-   Be respectful in this community

## Thank you

Thank you to [PHUSE](https://phuse.global/){target="_blank"} for supporting this endeavor. And thank you to ***YOU*** for your thoughtful contributions to the effort.
