# OSTCDA
Open Source Technology in Clinical Data Analysis

A significant amount of time and energy has been invested in recent years exploring the desirability (do we want it?), feasibility (can we do it?), and viability (is it worth it?) of integrating open source solutions into our clinical data pipelines which transform source data into clinical study reports and submission data packages. 

This repository will serve to collect and synthesize expert opinions and resources for a (hopefully) comprehensive set of [questions](https://github.com/phuse-org/OSTCDA/discussions) which arise as organizations travel this journey. 

The [discussions](https://github.com/phuse-org/OSTCDA/discussions) will provide citable (and sometimes quotable) input from industry experts, resulting in a “state of the union”-style manuscript that will help us move past questions that have already been sufficiently addressed and focus on those that remain. 

We invite you to navigate to the [Discussions section](https://github.com/phuse-org/OSTCDA/discussions) section to provide your thoughts, resources, or perspectives that help address any or all of the questions. If we've overlooked a key question - start up a new discussion thread!

## Purpose and Background

There are many questions around understanding and using open source for clinical data analysis. We want to create a comprehesive knowledge base about the "state of the union" and provide an overview and ideally also answers for core questions. We need and collect input from our community to compile the knowledge base, so please join the discussions to allow a broad and complete picutre.

If you like to know more, please join the R/Pharma talk "The State of Open Source Technology in Clinical Data Analysis, Reporting, and Submissions". The recording will be made available after the conference.
